# Generated by Django 2.1 on 2020-06-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
